name: Netlify Document Production Environment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publishOnMasterRelease:
    name: Deploying on Netlify Document Production Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
        working-directory: docs/document/website
      - name: Build document
        run: npm run build
        working-directory: docs/document/website
      - name: Install Netlify
        run: npm i netlify-cli --no-save
      - name: Deploying on Netlify Production Environment
        run: netlify deploy --prod --site d6b713a3-97ea-4e26-8f46-2b03242131b6 --debug
  algolia_recrawl:
    name: Algolia Recrawl
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2

      # We wait for a few seconds for the website to be successfully deployed
      - name: Sleep for 30s
        run: sleep 30

      - name: Algolia crawler creation and recrawl
        uses: algolia/algoliasearch-crawler-github-actions@v1
        id: crawler_push
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          crawler-name: "kuc-usaurus-v2"
          site-url: "https://example.com"
